# Generated by Django 3.0.3 on 2020-03-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin_url', models.URLField(max_length=400)),
                ('image', models.FileField(upload_to='products/masks/')),
                ('price', models.IntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
