# Generated by Django 3.0.3 on 2020-03-04 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='maskproduct',
            name='is_visible',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maskproduct',
            name='mask_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='image',
            field=models.FileField(blank=True, upload_to='products/masks/'),
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='origin_url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
