# Generated by Django 3.0.3 on 2020-03-01 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maskstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskproduct',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
