# Generated by Django 3.0.3 on 2020-03-01 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maskstore', '0003_auto_20200301_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskproduct',
            name='origin_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maskproduct',
            name='image',
            field=models.FileField(upload_to='products/masks/'),
        ),
    ]
